### PR TITLE
Integrate OpenVPN library

### PR DESCRIPTION
**Pull request by alalamav**
- Modifies the local openvpn Cordova plugin to use OpenVPN for Android as a library. The plugin's functionality remains.
- Adds instructions to build the openvpn library and include it in the project.
- Removes Colony's dependecy on the OpenVPN app being installed in the device.
- The cordova npm module has been updated to version > 6.0.0 in order to link against the library aar.

---

This change is [Reviewable](https://reviewable.io/reviews/uproxy/colony/34)

### CODE REVIEW

**Comment by jpevarnek** [comment]
Aah, I'm terribly sorry, I forgot this PR was in this repository.  Looking at this now.

**Comment by jpevarnek** [comment]
Hey, a few questions here, mostly around my lack of understanding in this area

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

_[client/plugin-src/cordova-plugin-openvpn/src/android/OpenVPN.java, line 34 [r1]](https://reviewable.io:443/reviews/uproxy/colony/34#-KKnTuX7HY-dWA-9znkE:-KKUUjQGDdF-qZ6tLMFm:-383323716) ([raw file](https://github.com/uproxy/colony/blob/ca882fe089793223b14decac8f3f73b4128eada0/client/plugin-src/cordova-plugin-openvpn/src/android/OpenVPN.java#L34)):_

> ``` Java
> 
> public class OpenVPN extends CordovaPlugin {
>   final static String LOG_TAG = "OpenVPNPlugin";
> ```

So, adding the disclaimer that I'm not a Java expect, but this seems like it should probably be the class name (or the class name should be this), am I totally wrong there?

---

_[client/plugin-src/cordova-plugin-openvpn/src/android/OpenVPN.java, line 36 [r1]](https://reviewable.io:443/reviews/uproxy/colony/34#-KKnTW5LsF6XzPjTyvUA:-KKUUiHHrOUujJ1pSz_a:1909252842) ([raw file](https://github.com/uproxy/colony/blob/ca882fe089793223b14decac8f3f73b4128eada0/client/plugin-src/cordova-plugin-openvpn/src/android/OpenVPN.java#L36)):_

> ``` Java
>   final static String LOG_TAG = "OpenVPNPlugin";
> 
>   private static final int PREPARE_VPN = 0;
> ```

This doesn't really give me any information about what the variable represents.  All I get from this is that the number 0 has something to do with preparing the VPN.  I think it would be good to have the name better reflect what it's actually doing

---

_[client/plugin-src/cordova-plugin-openvpn/src/android/OpenVPN.java, line 47 [r1]](https://reviewable.io:443/reviews/uproxy/colony/34#-KKUgMxGzhUGaLeT-rKj:-KKUgMxH82pFHNfHAKXA:-551720584) ([raw file](https://github.com/uproxy/colony/blob/ca882fe089793223b14decac8f3f73b4128eada0/client/plugin-src/cordova-plugin-openvpn/src/android/OpenVPN.java#L47)):_

> ``` Java
>     this.cordova.getActivity().startService(serviceIntent);
>     // Bind service.
>     Intent intent = new Intent(getBaseContext(), OpenVPNService.class);
> ```

Can you add more descriptive names for `intent` and `serviceIntent`?  I think it would be useful to have these closer reflect what you are using them for rather than just what they are.

---

_[client/plugin-src/cordova-plugin-openvpn/src/android/OpenVPN.java, line 55 [r1]](https://reviewable.io:443/reviews/uproxy/colony/34#-KKnUPXFx27ZPT8wE9Zi:-KKnUPXGz8h_WxUWuhxu:-1285810776) ([raw file](https://github.com/uproxy/colony/blob/ca882fe089793223b14decac8f3f73b4128eada0/client/plugin-src/cordova-plugin-openvpn/src/android/OpenVPN.java#L55)):_

> ``` Java
> 
>   @Override
>   public boolean execute(String action, JSONArray args, CallbackContext callbackContext) throws JSONException {
> ```

Can you add a comment here explaining what the return value actually means?

---

_[client/plugin-src/cordova-plugin-openvpn/src/android/OpenVPN.java, line 56 [r1]](https://reviewable.io:443/reviews/uproxy/colony/34#-KKnUWnvvX44K03IHrsV:-KKnUWnvvX44K03IHrsW:-1448859298) ([raw file](https://github.com/uproxy/colony/blob/ca882fe089793223b14decac8f3f73b4128eada0/client/plugin-src/cordova-plugin-openvpn/src/android/OpenVPN.java#L56)):_

> ``` Java
>   @Override
>   public boolean execute(String action, JSONArray args, CallbackContext callbackContext) throws JSONException {
>     if (action.equals("startVPN")) {
> ```

`startVPN` and `stopVPN` might be good things to make constants

---

_[client/plugin-src/cordova-plugin-openvpn/src/android/OpenVPN.java, line 57 [r1]](https://reviewable.io:443/reviews/uproxy/colony/34#-KKnUdeEQ6mr5tAZK2Tq:-KKnUdeEQ6mr5tAZK2Tr:-1829299832) ([raw file](https://github.com/uproxy/colony/blob/ca882fe089793223b14decac8f3f73b4128eada0/client/plugin-src/cordova-plugin-openvpn/src/android/OpenVPN.java#L57)):_

> ``` Java
>   public boolean execute(String action, JSONArray args, CallbackContext callbackContext) throws JSONException {
>     if (action.equals("startVPN")) {
>       String inlineConfig = args.getString(0);
> ```

Do you need to validate the number of arguments?

---

_[client/plugin-src/cordova-plugin-openvpn/src/android/OpenVPN.java, line 67 [r1]](https://reviewable.io:443/reviews/uproxy/colony/34#-KKn_2Ba9-DTq5sFpueE:-KKn_2Ba9-DTq5sFpueF:-911012083) ([raw file](https://github.com/uproxy/colony/blob/ca882fe089793223b14decac8f3f73b4128eada0/client/plugin-src/cordova-plugin-openvpn/src/android/OpenVPN.java#L67)):_

> ``` Java
>   }
> 
>   private ServiceConnection mConnection = new ServiceConnection() {
> ```

Is there an advantage to having the class implementation inline instead of doing it separately?

---

_[client/plugin-src/cordova-plugin-openvpn/src/android/OpenVPN.java, line 72 [r1]](https://reviewable.io:443/reviews/uproxy/colony/34#-KKnUzJrDm0ah3GkRTPz:-KKnUzJrDm0ah3GkRTQ-:519072821) ([raw file](https://github.com/uproxy/colony/blob/ca882fe089793223b14decac8f3f73b4128eada0/client/plugin-src/cordova-plugin-openvpn/src/android/OpenVPN.java#L72)):_

> ``` Java
>                                    IBinder service) {
>       OpenVPNService.LocalBinder binder = (OpenVPNService.LocalBinder)service;
>       mService = binder.getService();
> ```

I had to go back and check where `mService` was at this point, might be useful to have it named something closer to `mRunningVpnService` or something closer to that (I'm actually not exactly sure what it is).

---

_[client/plugin-src/cordova-plugin-openvpn/src/android/OpenVPN.java, line 76 [r1]](https://reviewable.io:443/reviews/uproxy/colony/34#-KKnVAPvZJs_ndmK9cRN:-KKnVAPvZJs_ndmK9cRO:1290241133) ([raw file](https://github.com/uproxy/colony/blob/ca882fe089793223b14decac8f3f73b4128eada0/client/plugin-src/cordova-plugin-openvpn/src/android/OpenVPN.java#L76)):_

> ``` Java
> 
>     @Override
>     public void onServiceDisconnected(ComponentName arg0) {
> ```

What is `arg0` in this case?

---

_[client/plugin-src/cordova-plugin-openvpn/src/android/OpenVPN.java, line 77 [r1]](https://reviewable.io:443/reviews/uproxy/colony/34#-KKUh5pA4tsJZ2OMKGOM:-KKUh5pA4tsJZ2OMKGON:-1662701634) ([raw file](https://github.com/uproxy/colony/blob/ca882fe089793223b14decac8f3f73b4128eada0/client/plugin-src/cordova-plugin-openvpn/src/android/OpenVPN.java#L77)):_

> ``` Java
>     @Override
>     public void onServiceDisconnected(ComponentName arg0) {
>         Log.i(LOG_TAG, "VPN disconnected.");
> ```

I think you have an extra level of indentation here

---

_[client/plugin-src/cordova-plugin-openvpn/src/android/OpenVPN.java, line 83 [r1]](https://reviewable.io:443/reviews/uproxy/colony/34#-KKnZcdO8HVKa7vLfwor:-KKnZcdO8HVKa7vLfwos:1442672152) ([raw file](https://github.com/uproxy/colony/blob/ca882fe089793223b14decac8f3f73b4128eada0/client/plugin-src/cordova-plugin-openvpn/src/android/OpenVPN.java#L83)):_

> ``` Java
> 
>   private void prepareVPNService() {
>     if (VpnService.prepare(getBaseContext()) == null) {
> ```

It looks to me like the android API is saying to launch the intent returned by this if you get one back, why are we not doing that? (can you add a comment)

---

_[client/plugin-src/cordova-plugin-openvpn/src/android/OpenVPN.java, line 96 [r1]](https://reviewable.io:443/reviews/uproxy/colony/34#-KKnW5mNetglmdaW-UzV:-KKnW5mNetglmdaW-UzW:982244644) ([raw file](https://github.com/uproxy/colony/blob/ca882fe089793223b14decac8f3f73b4128eada0/client/plugin-src/cordova-plugin-openvpn/src/android/OpenVPN.java#L96)):_

> ``` Java
>       cp.parseConfig(new StringReader(inlineConfig));
>       VpnProfile vp = cp.convertProfile();
>       vp.mName = "OpenVPN";
> ```

My understanding is that the `m` means this field is non-public, is there a different way we should be setting it?

---

_[client/plugin-src/cordova-plugin-openvpn/src/android/OpenVPN.java, line 117 [r1]](https://reviewable.io:443/reviews/uproxy/colony/34#-KKnWfF24Y1wSbji2lx1:-KKnWfF24Y1wSbji2lx2:-1359412400) ([raw file](https://github.com/uproxy/colony/blob/ca882fe089793223b14decac8f3f73b4128eada0/client/plugin-src/cordova-plugin-openvpn/src/android/OpenVPN.java#L117)):_

> ``` Java
>     int needPassword = vp.needUserPWInput(false);
> 
>     if(vpnPermissionIntent != null || needPassword != 0){
> ```

It looks to me like both of these got set above, can you at least add a comment explaining this?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/uproxy/colony/34#-:-KKn_8403oy926wq2Y6U:-1270093314)_

**Comment by alalamav** [comment]
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

_[client/plugin-src/cordova-plugin-openvpn/src/android/OpenVPN.java, line 34 [r1]](https://reviewable.io:443/reviews/uproxy/colony/34#-KKnTuX7HY-dWA-9znkE:-KM0WGRNydZxRjBN8sNP:-499146009) ([raw file](https://github.com/uproxy/colony/blob/ca882fe089793223b14decac8f3f73b4128eada0/client/plugin-src/cordova-plugin-openvpn/src/android/OpenVPN.java#L34)):_
<details><summary>

<i>Previously, jpevarnek (Jonathan Pevarnek) wrote…</i></summary>



> So, adding the disclaimer that I'm not a Java expect, but this seems like it should probably be the class name (or the class name should be this), am I totally wrong there?
> </details>
> Done.

---

_[client/plugin-src/cordova-plugin-openvpn/src/android/OpenVPN.java, line 36 [r1]](https://reviewable.io:443/reviews/uproxy/colony/34#-KKnTW5LsF6XzPjTyvUA:-KM1AtUd_uC7_eAoe8yg:-499146009) ([raw file](https://github.com/uproxy/colony/blob/ca882fe089793223b14decac8f3f73b4128eada0/client/plugin-src/cordova-plugin-openvpn/src/android/OpenVPN.java#L36)):_
<details><summary>

<i>Previously, jpevarnek (Jonathan Pevarnek) wrote…</i></summary>



> This doesn't really give me any information about what the variable represents.  All I get from this is that the number 0 has something to do with preparing the VPN.  I think it would be good to have the name better reflect what it's actually doing
> </details>
> Done.

---

_[client/plugin-src/cordova-plugin-openvpn/src/android/OpenVPN.java, line 47 [r1]](https://reviewable.io:443/reviews/uproxy/colony/34#-KKUgMxGzhUGaLeT-rKj:-KM0Xp-Y3Gv8A81M-uBV:-499146009) ([raw file](https://github.com/uproxy/colony/blob/ca882fe089793223b14decac8f3f73b4128eada0/client/plugin-src/cordova-plugin-openvpn/src/android/OpenVPN.java#L47)):_
<details><summary>

<i>Previously, jpevarnek (Jonathan Pevarnek) wrote…</i></summary>



> Can you add more descriptive names for `intent` and `serviceIntent`?  I think it would be useful to have these closer reflect what you are using them for rather than just what they are.
> </details>
> Done.

---

_[client/plugin-src/cordova-plugin-openvpn/src/android/OpenVPN.java, line 55 [r1]](https://reviewable.io:443/reviews/uproxy/colony/34#-KKnUPXFx27ZPT8wE9Zi:-KM0ZJ8ikhk7y7cPEqKX:-499146009) ([raw file](https://github.com/uproxy/colony/blob/ca882fe089793223b14decac8f3f73b4128eada0/client/plugin-src/cordova-plugin-openvpn/src/android/OpenVPN.java#L55)):_
<details><summary>

<i>Previously, jpevarnek (Jonathan Pevarnek) wrote…</i></summary>



> Can you add a comment here explaining what the return value actually means?
> </details>
> Done.

---

_[client/plugin-src/cordova-plugin-openvpn/src/android/OpenVPN.java, line 56 [r1]](https://reviewable.io:443/reviews/uproxy/colony/34#-KKnUWnvvX44K03IHrsV:-KM0YoBaHXn2k3q0mifc:-499146009) ([raw file](https://github.com/uproxy/colony/blob/ca882fe089793223b14decac8f3f73b4128eada0/client/plugin-src/cordova-plugin-openvpn/src/android/OpenVPN.java#L56)):_
<details><summary>

<i>Previously, jpevarnek (Jonathan Pevarnek) wrote…</i></summary>



> `startVPN` and `stopVPN` might be good things to make constants
> </details>
> Done.

---

_[client/plugin-src/cordova-plugin-openvpn/src/android/OpenVPN.java, line 57 [r1]](https://reviewable.io:443/reviews/uproxy/colony/34#-KKnUdeEQ6mr5tAZK2Tq:-KM0Yr_k3ITfJLNVx5b5:-499146009) ([raw file](https://github.com/uproxy/colony/blob/ca882fe089793223b14decac8f3f73b4128eada0/client/plugin-src/cordova-plugin-openvpn/src/android/OpenVPN.java#L57)):_
<details><summary>

<i>Previously, jpevarnek (Jonathan Pevarnek) wrote…</i></summary>



> Do you need to validate the number of arguments?
> </details>
> Done.

---

_[client/plugin-src/cordova-plugin-openvpn/src/android/OpenVPN.java, line 67 [r1]](https://reviewable.io:443/reviews/uproxy/colony/34#-KKn_2Ba9-DTq5sFpueE:-KM0ZXuYpa-z95dN8lLR:423751586) ([raw file](https://github.com/uproxy/colony/blob/ca882fe089793223b14decac8f3f73b4128eada0/client/plugin-src/cordova-plugin-openvpn/src/android/OpenVPN.java#L67)):_
<details><summary>

<i>Previously, jpevarnek (Jonathan Pevarnek) wrote…</i></summary>



> Is there an advantage to having the class implementation inline instead of doing it separately?
> </details>
> This seems to be the standard way of defining it - every example I've seen does it like this.

---

_[client/plugin-src/cordova-plugin-openvpn/src/android/OpenVPN.java, line 72 [r1]](https://reviewable.io:443/reviews/uproxy/colony/34#-KKnUzJrDm0ah3GkRTPz:-KM0Zl23y3rT-cY_4e_v:-499146009) ([raw file](https://github.com/uproxy/colony/blob/ca882fe089793223b14decac8f3f73b4128eada0/client/plugin-src/cordova-plugin-openvpn/src/android/OpenVPN.java#L72)):_
<details><summary>

<i>Previously, jpevarnek (Jonathan Pevarnek) wrote…</i></summary>



> I had to go back and check where `mService` was at this point, might be useful to have it named something closer to `mRunningVpnService` or something closer to that (I'm actually not exactly sure what it is).
> </details>
> Done.

---

_[client/plugin-src/cordova-plugin-openvpn/src/android/OpenVPN.java, line 76 [r1]](https://reviewable.io:443/reviews/uproxy/colony/34#-KKnVAPvZJs_ndmK9cRN:-KM0aLZm4hBl8CJHDp91:888647890) ([raw file](https://github.com/uproxy/colony/blob/ca882fe089793223b14decac8f3f73b4128eada0/client/plugin-src/cordova-plugin-openvpn/src/android/OpenVPN.java#L76)):_
<details><summary>

<i>Previously, jpevarnek (Jonathan Pevarnek) wrote…</i></summary>



> What is `arg0` in this case?
> </details>
> Clarified the argument name. https://developer.android.com/reference/android/content/ServiceConnection.html#onServiceDisconnected(android.content.ComponentName)

---

_[client/plugin-src/cordova-plugin-openvpn/src/android/OpenVPN.java, line 77 [r1]](https://reviewable.io:443/reviews/uproxy/colony/34#-KKUh5pA4tsJZ2OMKGOM:-KM0gMEfbVcHiGBvb7Kt:-499146009) ([raw file](https://github.com/uproxy/colony/blob/ca882fe089793223b14decac8f3f73b4128eada0/client/plugin-src/cordova-plugin-openvpn/src/android/OpenVPN.java#L77)):_
<details><summary>

<i>Previously, jpevarnek (Jonathan Pevarnek) wrote…</i></summary>



> I think you have an extra level of indentation here
> </details>
> Done.

---

_[client/plugin-src/cordova-plugin-openvpn/src/android/OpenVPN.java, line 83 [r1]](https://reviewable.io:443/reviews/uproxy/colony/34#-KKnZcdO8HVKa7vLfwor:-KM0gNYtToW0ue4ypynb:1452569858) ([raw file](https://github.com/uproxy/colony/blob/ca882fe089793223b14decac8f3f73b4128eada0/client/plugin-src/cordova-plugin-openvpn/src/android/OpenVPN.java#L83)):_
<details><summary>

<i>Previously, jpevarnek (Jonathan Pevarnek) wrote…</i></summary>



> It looks to me like the android API is saying to launch the intent returned by this if you get one back, why are we not doing that? (can you add a comment)
> </details>
> I'm removing this method in favor of preparing the VPN service on every start. startVPNWithProfile requests the appropriate permissions from the user if VPN has not been prepared.

---

_[client/plugin-src/cordova-plugin-openvpn/src/android/OpenVPN.java, line 96 [r1]](https://reviewable.io:443/reviews/uproxy/colony/34#-KKnW5mNetglmdaW-UzV:-KM1B67rcSDPeP1Kw04D:-61191037) ([raw file](https://github.com/uproxy/colony/blob/ca882fe089793223b14decac8f3f73b4128eada0/client/plugin-src/cordova-plugin-openvpn/src/android/OpenVPN.java#L96)):_
<details><summary>

<i>Previously, jpevarnek (Jonathan Pevarnek) wrote…</i></summary>



> My understanding is that the `m` means this field is non-public, is there a different way we should be setting it?
> </details>
> I think the m conventionally stands for member, in this case it's a public one.

---

_[client/plugin-src/cordova-plugin-openvpn/src/android/OpenVPN.java, line 117 [r1]](https://reviewable.io:443/reviews/uproxy/colony/34#-KKnWfF24Y1wSbji2lx1:-KM1BTaJDyX0hnKZrL20:-1040809739) ([raw file](https://github.com/uproxy/colony/blob/ca882fe089793223b14decac8f3f73b4128eada0/client/plugin-src/cordova-plugin-openvpn/src/android/OpenVPN.java#L117)):_
<details><summary>

<i>Previously, jpevarnek (Jonathan Pevarnek) wrote…</i></summary>



> It looks to me like both of these got set above, can you at least add a comment explaining this?
> </details>
> VPN will be prepared here, if user hasn't granted permissions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/uproxy/colony/34)_

**Comment by jpevarnek** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[client/plugin-src/cordova-plugin-openvpn/src/android/OpenVPN.java, line 52 [r2]](https://reviewable.io:443/reviews/uproxy/colony/34#-KM5tRfAh42mAoiFimJ1:-KM5tRfAh42mAoiFimJ2:-1391204971) ([raw file](https://github.com/uproxy/colony/blob/9373e5fa264b7518addeadfaff53e491b6d993ea/client/plugin-src/cordova-plugin-openvpn/src/android/OpenVPN.java#L52)):_

> ``` Java
>     if (action.equals(ACTION_START_VPN)) {
>       if (args.length() < 1) {
>         callbackContext.error("Cannot start VPN without config.");
> ```

Stylistic thing: this takes a tiny bit of effort to read and see that we are returning true afterwards.  I think it might be easier to understand if you had:

```
if (args.length() < 1) {
  error(...);
  return true;
}

startVPN(...);
return true;
```

That's totally personal preference, your choice on whether to consider it though.

Also, does it mean anything if we get more than one argument?

---

_[client/plugin-src/cordova-plugin-openvpn/src/android/OpenVPN.java, line 121 [r2]](https://reviewable.io:443/reviews/uproxy/colony/34#-KM5uqPzQmtWQagS0I4G:-KM5uqPzQmtWQagS0I4H:985455547) ([raw file](https://github.com/uproxy/colony/blob/9373e5fa264b7518addeadfaff53e491b6d993ea/client/plugin-src/cordova-plugin-openvpn/src/android/OpenVPN.java#L121)):_

> ``` Java
>     Intent vpnPermissionIntent = VpnService.prepare(getBaseContext());
>     int needPassword = vp.needUserPWInput(false);
>     if(vpnPermissionIntent != null || needPassword != 0){
> ```

nit: looks like indentation here is a bit off from the rest of the code

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/uproxy/colony/34)_

**Comment by alalamav** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[client/plugin-src/cordova-plugin-openvpn/src/android/OpenVPN.java, line 52 [r2]](https://reviewable.io:443/reviews/uproxy/colony/34#-KM5tRfAh42mAoiFimJ1:-KM6433nj6rYM1Z4n8OW:-1501642915) ([raw file](https://github.com/uproxy/colony/blob/9373e5fa264b7518addeadfaff53e491b6d993ea/client/plugin-src/cordova-plugin-openvpn/src/android/OpenVPN.java#L52)):_
<details><summary>

<i>Previously, jpevarnek (Jonathan Pevarnek) wrote…</i></summary>



> Stylistic thing: this takes a tiny bit of effort to read and see that we are returning true afterwards.  I think it might be easier to understand if you had:
> 
> ```
> if (args.length() < 1) {
>   error(...);
>   return true;
> }
> 
> startVPN(...);
> return true;
> ```
> 
> That's totally personal preference, your choice on whether to consider it though.
> 
> Also, does it mean anything if we get more than one argument?
> </details>
> Done. I think your suggestion is clearer.

---

_[client/plugin-src/cordova-plugin-openvpn/src/android/OpenVPN.java, line 121 [r2]](https://reviewable.io:443/reviews/uproxy/colony/34#-KM5uqPzQmtWQagS0I4G:-KM64725p2zx-Bdm_eMs:-499146009) ([raw file](https://github.com/uproxy/colony/blob/9373e5fa264b7518addeadfaff53e491b6d993ea/client/plugin-src/cordova-plugin-openvpn/src/android/OpenVPN.java#L121)):_
<details><summary>

<i>Previously, jpevarnek (Jonathan Pevarnek) wrote…</i></summary>



> nit: looks like indentation here is a bit off from the rest of the code
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/uproxy/colony/34)_

**Comment by jpevarnek** [comment]
:thumbsup:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[client/plugin-src/cordova-plugin-openvpn/src/android/OpenVPN.java, line 121 [r2]](https://reviewable.io:443/reviews/uproxy/colony/34#-KM5uqPzQmtWQagS0I4G:-KM65se3O06bmh9bC60D:414423308) ([raw file](https://github.com/uproxy/colony/blob/9373e5fa264b7518addeadfaff53e491b6d993ea/client/plugin-src/cordova-plugin-openvpn/src/android/OpenVPN.java#L121)):_
<details><summary>

<i>Previously, albertolalama (alberto lalama) wrote…</i></summary>



> Done.
> </details>
> (oops, meant spacing, but thanks for getting what I meant!) :)

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/uproxy/colony/34#-:-KM65y7ppgfet6O1A7Jy:1393940045)_

**Pull request merged**
